# Generated by Django 4.2 on 2025-11-11 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('satisfaction_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Rate your overall satisfaction (1-10)')),
                ('hydration_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='How hydrated does your skin feel? (1=Very dry, 10=Very hydrated)')),
                ('clarity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Skin clarity/texture (1=Poor, 10=Excellent)')),
                ('breakouts', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Breakout frequency (1=Very frequent, 10=None)')),
                ('redness', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Redness/irritation level (1=Very red, 10=No redness)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about your skin today', null=True)),
                ('routine_followed', models.BooleanField(default=True, help_text='Did you follow your routine today?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skin Progress Entry',
                'verbose_name_plural': 'Skin Progress Entries',
                'ordering': ['-date'],
            },
        ),
    ]
