# Generated by Django 4.2 on 2025-11-14 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_remove_product_link_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkincareReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Skincare Routine', max_length=200)),
                ('reminder_type', models.CharField(choices=[('morning', 'Morning Routine'), ('evening', 'Evening Routine'), ('both', 'Both Morning & Evening'), ('custom', 'Custom Time')], default='morning', max_length=20)),
                ('time', models.TimeField(help_text='Time for reminder')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('custom', 'Custom Days')], default='daily', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or steps')),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skincare_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
